# Paquetes a revisar en busca de clases anotadas como componentes.
# Un componente es un objeto cuyo ciclo de vida está gestionado por Spring IoC.
app.component.packages-to-scan=es.thefactory.hellospringdatajpa

# Paquetes a revisar en busca de clases anotadas como entidades JPA.
jpa.entity.packages-to-scan=es.thefactory.hellospringdatajpa

# Paquetes a revisar en busca de interfaces anotadas como repositorios JPA.
jpa.repository.packages-to-scan=es.thefactory.hellospringdatajpa
